apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onsd/ArgoCD-.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
